swagger: '2.0'
host: HOST
basePath: /buonodomsrv/api/v1
schemes:
  - https
info:
  title: 'Buono Domiciliarita (BOZZA)'
  version: 0.0.18
  description: |

    # Avvertenze
    ---


    # Domande
    ---

    # Prototipo Interfaccia
   

   
    ## Versione 0.0.1 (10 Mag 2022)
    * Prima implementazione

paths:
  '/servizio-attivo':
    get:
      summary: Raggiungibilità
      description: |
        Serve per verificare se il servizio risponde o meno
      produces:
        - application/json
      parameters:
        - $ref: '#/parameters/header_x_request_id'
        - $ref: '#/parameters/header_x_forwarded_for'
        - $ref: '#/parameters/header_x_codice_servizio'
      responses:
        '200':
          description: |
            La richiesta è andata a buon fine quindi il servizio è online
          headers:
            X-Request-ID:
              type: string
              description: Ritorno del parametro ricevuto nella request.
          schema:
            $ref: '#/definitions/model_info_servizio'

parameters:
  header_shib_identita_codice_fiscale:
    in: header
    name: Shib-Identita-CodiceFiscale
    description: Contiene il codice fiscale dell'utente loggato ottenuto tramite shibboleth
    type: string
    required: true
  header_x_request_id:
    in: header
    name: X-Request-Id
    description: >-
      Contiene un id univoco (`uuid v4`) della chiamata HTTP che viene generato
      dal front-end, viene propagato agli strati successivi e viene restituito
      al front-end assieme alla response, permettendo così di tracciare l'intero
      ciclo di vita della richiesta
    type: string
    required: true
  header_x_forwarded_for:
    in: header
    name: X-Forwarded-For
    description: |
      Contiene l'elenco degli ip che hanno gestito la richiesta.
      Utile per i log e l'audit.
      Il formato della stringa è
      ```
      <ip-front-end>, <ip-primo-server>, ..., <ip-ultimo-server>
      ```
      Es. `10.10.10.10, 10.38.45.68, 10.128.69.244`
    type: string
    required: true
  header_x_codice_servizio:
    in: header
    name: X-Codice-Servizio
    description: Contiene una stringa identificativa del servizio chiamante (es.COD)
    type: string
    required: true
  header_x_codice_verticale:
    in: header
    name: X-Codice-Verticale
    description: Contiene una stringa identificativa del verticale chiamante (es.COD)
    type: string
    required: true
  path_cit_id:
    in: path
    name: 'id_assistito'
    type: string
    required: true
    description:
      Il codice fiscale dell'assistito


responses:
  BadRequest:
    description:
      La richiesta fatta dal client è errata. Ad esempio non sono stati passati
      tutti i campi obbligatori, uno dei campi è di un tipo non valido,
      formattazione dei filtri errata ecc.
    headers:
      X-Request-ID:
        type: string
        description: Ritorno del parametro ricevuto nella request.
    schema:
      $ref: '#/definitions/errore'
  Forbidden:
    description:
      L'utente non ha i permessi necessari per visualizzare queste risorse. <br>
      Ad esempio un utente che sta provando ad ottenere le ricette di un altro
      utente senza averne la delega.
    headers:
      X-Request-ID:
        type: string
        description: Ritorno del parametro ricevuto nella request.
    schema:
      $ref: '#/definitions/errore'
  NotFound:
    description:
      La risorsa cercata non è stata trovata. <br> Questo errore viene
      restituito quando si prova ad accedere alla singola risorsa e questa non
      esiste. <br> Nel caso in cui si prova ad ottenere una lista e non ci sono
      elementi, restituire 200 con un array vuoto
    headers:
      X-Request-ID:
        type: string
        description: Ritorno del parametro ricevuto nella request.
    schema:
      $ref: '#/definitions/errore'
  InternalServerError:
    description:
      Si è verificato un'errore interno del server. (es. null pointer exception,
      connessione al DB saltata ecc)
    headers:
      X-Request-ID:
        type: string
        description: Ritorno del parametro ricevuto nella request.
    schema:
      $ref: '#/definitions/errore'
definitions:
  model_info_servizio:
    title: 'Info servizio'
    type: object
    properties:
      nome:
        type: string
        description: nome del servizio
      descrizione:
        type: string
        description: descrizione del servizio
      data:
        type: string
        format: date
      servizio_attivo:
        type: boolean
        description: boolean di utilita per eventuali test

  errore:
    title: '[ERRORE] Generico'
    type: object
    properties:
      status:
        type: integer
      code:
        type: string
        description: Codice univoco di errore interno
      title:
        type: string
        description: Testo dell'errore da mostrare al cittadino
      detail:
        type: array
        items:
          $ref: '#/definitions/errore_dettaglio'
      links:
        type: array
        items:
          type: string
  errore_dettaglio:
    title: '[ERRORE] Dettaglio'
    type: object
    properties:
      chiave:
        type: string
        description: Codice univoco di errore interno
      valore:
        type: string
        description: Testo dell'errore da mostrare al cittadino
